openapi: 3.0.0
info:
  title: Proxy API
  version: 1.0.0
  description: Simple proxy API using Express

paths:
  /api/get/{id}:
    get:
      summary: Retrieve a post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The post ID
      responses:
        200:
          description: A post object

  /api/post:
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                userId:
                  type: integer
      responses:
        201:
          description: Created post
